###############################################################
#                   Authelia configuration                    #
###############################################################

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: a_very_important_secret
default_redirection_url: https://whoami.arsalanses.ir

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: auth.arsalanses.ir
  period: 30
  skew: 1

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  # file:
  #   path: /config/users_database.yml
  #   # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
  #   password:
  #     algorithm: argon2id
  #     iterations: 1
  #     salt_length: 16
  #     parallelism: 8
  #     memory: 1024 # blocks this much of the RAM. Tune this.
  ldap:
    implementation: custom
    url: ldap://lldap:3890
    timeout: 5s
    start_tls: false
    # tls:
    #  skip_verify: false
    #  minimum_version: TLS1.2
    base_dn: dc=arsalanses,DC=ir
    username_attribute: uid
    additional_users_dn: OU=people
    # To allow sign in both with username and email, one can use a filter like
    # (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: OU=groups
    groups_filter: (member={dn})
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    # The username and password of the admin or service user.
    user: UID=admin,OU=people,DC=arsalanses,DC=ir
    password: "REPLACE_WITH_PASSWORD"

access_control:
  # deny
  default_policy: one_factor
  rules:
    # Rules applied to everyone
    - domain: whoami.arsalanses.ir
      policy: bypass
    - domain: traefik-auth.arsalanses.ir
      policy: one_factor
    - domain: whoamis.arsalanses.ir
      policy: two_factor
    # - domain: heimdall.arsalanses.ir
    #   policy: one_factor
    # - domain: nextcloud.arsalanses.ir
    #   policy: one_factor

identity_providers:
  oidc:
    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICXAIBAAKBgQCb1h5UyQjTWXykCjk4yiWCM3GqrVSlweRCdJoC8Ta8HHbgXKwi
      BVqXma1YAuIkl5plcKJKHT7NzZyRI2bLu3+W+La9GlzLkWrGXzhT1r+WkYjmZUmq
      xqx521R8a6FyNxB59LkV+ef0xCeGfXLsYfxHaNhntDxt91deI8qW9tTGpQIDAQAB
      AoGAYL6nCd/ceMk/Vd968sScUJ57XIhK2rTqbk9RJa52WoYZTuR5gI1uVltzgAYa
      OrlbgspQFk7dpIqXPouJz8VRSYEvYkd3HzEyz5cCkPYVnumYbQHIyh7wmbyks+Oi
      sRFb/fPz7/UHA3ynJ7h4LpZtSciQ6uk6HRdwDlDjK2eQyAECQQDeBKnbuv1FeMuv
      ssff2mTa5+67grEuu17Ftz4RatOkvzFSXUoEE0YTvLhdUmL4Q8rT+hdepzQ3jNMU
      f850cZOlAkEAs7BA+5mSV/aOD2MQ9mnWeG3o3OU9kzFrVqi6xSMylhx8Hc9iC7Vl
      FhseqqeFSBJCyIWmIeFyKrluJd8SygP3AQJAaFLSqfBckGdpdp7QcqyBladEM5H+
      xdG/f7JSFQcYeiJo/6XcYLvZwu57x0YuQTBBv4eVsaFp1Ox0Rv6jOW4hDQJAJD/J
      TDh16mLl07rTgDJnvtHFaVKhsmEE222ciAqKuPe0Hjto9x2379a2wAydeaWdbWBw
      3GLjqjTQQLmYy8IzAQJBAKqeT6ls591EfhPklF+JRfFnMfJoZN+C05TCEbPM4omd
      wE/JWV7sG96PNI66JXcfVPxMSugLuYyYYhN8dY7U8O4=
      -----END RSA PRIVATE KEY-----
    clients:
    - id: nextcloud
      description: NextCloud
      secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  # The digest of 'insecure_secret'.
      public: false
      authorization_policy: two_factor
      redirect_uris:
        - https://auth.arsalanses.ir/index.php/apps/sociallogin/custom_oidc/Authelia
        # - https://nextcloud.arsalanses.ir/apps/oidc_login/oidc
      scopes:
        - openid
        - profile
        - email
        - groups
      userinfo_signing_algorithm: none

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # Used a different secret, but the same site as jwt_secret above.
  secret: SECRET_GOES_HERE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: arsalanses.ir # Should match whatever your root protected domain is

  # redis:
  #   host: redis
  #   port: 6379
  #   # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
  #   # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
  # smtp:
  #   username: SMTP_USERNAME
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   # password: # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   host: SMTP_HOST
  #   port: 587 #465
  #   sender: batman@example.com # customize for your setup
